export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";
export const GET_TODOS_SUCCEES = "GET_TODOS_SUCCEES";
export const GET_TODOS_FAILURE = "GET_TODOS_FAILURE";

export const SET_TODOS_REQUEST = "SET_TODOS_REQUEST";
export const SET_TODOS_SUCCEES = "SET_TODOS_SUCCEES";
export const SET_TODOS_FAILURE = "SET_TODOS_FAILURE";

export const DELETE_TODOS_REQUEST = "DELETE_TODOS_REQUEST";
export const DELETE_TODOS_SUCCEES = "DELETE_TODOS_SUCCEES";
export const DELETE_TODOS_FAILURE = "DELETE_TODOS_FAILURE";

export const TOGGLE_TODOS_REQUEST = "TOGGLE_TODOS_REQUEST";
export const TOGGLE_TODOS_SUCCEES = "TOGGLE_TODOS_SUCCEES";
export const TOGGLE_TODOS_FAILURE = "TOGGLE_TODOS_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";