export const ActionTypes = {
  GET_TODOS_REQUEST: "GET_TODOS_REQUEST",
  GET_TODOS_SUCCESS: "GET_TODOS_SUCCESS",
  GET_TODOS_FAILURE: "GET_TODOS_FAILURE",
  SET_TODOS_REQUEST: "SET_TODOS_REQUEST",
  SET_TODOS_SUCCESS: "SET_TODOS_SUCCESS",
  SET_TODOS_FAILURE: "SET_TODOS_FAILURE",
  DELETE_TODOS_REQUEST: "DELETE_TODOS_REQUEST",
  DELETE_TODOS_SUCCESS: "DELETE_TODOS_SUCCESS",
  DELETE_TODOS_FAILURE: "DELETE_TODOS_FAILURE",
  EDIT_TODOS_REQUEST: "EDIT_TODOS_REQUEST",
  EDIT_TODOS_SUCCESS: "EDIT_TODOS_SUCCESS",
  EDIT_TODOS_FAILURE: "EDIT_TODOS_FAILURE",
};
